---
# Set hostname to loopback
- name: Set hostname for loopback interface
  lineinfile: dest=/etc/hosts line="127.0.1.1 {{ item }}"
  with_items: virtual_hosts
# Update apt repository
- name: Update package cache
  apt: update_cache=yes
# Install all system packages using apt
- name: Install system packages
  apt: name={{ item }}
  with_items: system_packages
- name: Copy bashrc to global etc
  copy: src=bashrc dest=/etc/bash.bashrc
- name: Copy bashrc to vagrant user
  copy: src=bashrc dest=/home/vagrant owner=vagrant group=vagrant mode="u+x"
