---
# Set hostname to loopback
- name: Set hostname for loopback interface
  lineinfile: dest=/etc/hosts line="127.0.1.1 {{ item }}"
  with_items: virtual_hosts
# Update apt repository
- name: Update package cache
  apt: update_cache=yes
# Install all system packages using apt
- name: Install system packages
  apt: name={{ item }}
  with_items: system_packages
