---
# Install mysql server
- name: Install mysql-server
  apt: name=mysql-server
# Create MySQL Database
- name: Create MySQL DB
  mysql_db: name={{ item }} state=present
  with_items: mysql_db
# Configure MySQL User
- name: Add MySQL User
  mysql_user: name={{ mysql_user }} password={{ mysql_pass }} priv=*.*:ALL state=present
