---
# Install ioncube

- name: Check if ioncube is already installed
  stat: path=/usr/lib/php5/extensions/ioncube.so
  register: ioncube_installed
- name: Download ioncube
  get_url: url={{ioncube_url}} dest=/tmp/ioncube.tar.gz
  when: ioncube_installed.exists == False
- name: Unpack ioncube
  command: tar -xvzf /tmp/ioncube.tar.gz chdir=/tmp/ioncube
  when: ioncube_installed.exists == False
